# Generated by Django 4.2.17 on 2025-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0012_alter_game_cost_alter_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
