# Generated by Django 4.2.17 on 2025-01-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0016_alter_buyer_balance_alter_game_cost_alter_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
