# Generated by Django 4.2.17 on 2025-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0018_alter_buyer_balance_alter_game_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
